//! The `harbor.lock` lockfile: struct, (de)serialization, and generation
//! (SPEC.md §7).
//!
//! `harbor.lock` is generated by Harbor, never hand-authored. It records
//! metadata required to reproduce and validate a specific built package —
//! it never replaces or duplicates a native lockfile (`uv.lock`,
//! `package-lock.json`, etc), only checksums it.

use std::io;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::checksum::{sha256_file, sha256_hex};
use crate::manifest::Manifest;

/// Errors that can occur while parsing or generating a `harbor.lock`.
#[derive(Debug, Error)]
pub enum LockfileError {
    /// The TOML itself is malformed, or a required field is missing/mistyped.
    #[error("failed to parse harbor.lock: {0}")]
    Parse(#[from] toml::de::Error),

    /// Failed to serialize a [`Lockfile`] back to TOML (should not normally
    /// happen for a well-formed struct, but the conversion is fallible).
    #[error("failed to serialize harbor.lock: {0}")]
    Serialize(#[from] toml::ser::Error),

    /// The manifest declares a native lockfile (`dependencies.lockfile`) but
    /// it does not exist on disk under the package root.
    #[error(
        "manifest declares native lockfile {declared:?} but it was not found at {resolved}"
    )]
    NativeLockfileMissing { declared: String, resolved: String },

    /// I/O failure while hashing a file (e.g. the native lockfile, or one of
    /// the package's included files).
    #[error("I/O error computing checksum for {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: io::Error,
    },
}

/// The full `harbor.lock` lockfile (SPEC.md §7.2).
///
/// Serializes to kebab-case TOML keys. `native-lockfile`,
/// `native-lock-checksum`, and `package-checksum` are omitted from the
/// output entirely when `None` (they are absent, not `null`, in a
/// freshly-`skeleton`'d lockfile).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct Lockfile {
    pub spec_version: u64,
    pub harbor_version: String,
    pub package_version: String,
    pub generated_at: String,
    pub native_manifest: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_lockfile: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_lock_checksum: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub package_checksum: Option<String>,
}

impl Lockfile {
    /// Parse a `harbor.lock` document from its string contents.
    pub fn from_toml_str(s: &str) -> Result<Lockfile, LockfileError> {
        let lockfile: Lockfile = toml::from_str(s)?;
        Ok(lockfile)
    }

    /// Serialize this lockfile to its canonical TOML representation.
    pub fn to_toml_string(&self) -> Result<String, LockfileError> {
        let s = toml::to_string(self)?;
        Ok(s)
    }

    /// Associated-function alias for [`skeleton`], so callers may spell it
    /// either `Lockfile::skeleton(&manifest)` or `lockfile::skeleton(&manifest)`.
    pub fn skeleton(manifest: &Manifest) -> Lockfile {
        skeleton(manifest)
    }
}

/// Build a `harbor.lock` skeleton from a manifest (used by `harbor init`):
/// every field that can be known statically is populated, and both
/// checksums are left `None` since no package has been built yet.
pub fn skeleton(manifest: &Manifest) -> Lockfile {
    Lockfile {
        spec_version: manifest.spec_version,
        harbor_version: crate::HARBOR_VERSION.to_string(),
        package_version: manifest.version.clone(),
        generated_at: now_iso8601(),
        native_manifest: manifest.dependencies.manifest.clone(),
        native_lockfile: manifest.dependencies.lockfile.clone(),
        native_lock_checksum: None,
        package_checksum: None,
    }
}

/// Generate a fully-populated `harbor.lock` for a package about to be built
/// (SPEC.md §7.3, `harbor push`).
///
/// `package_root` is the directory containing `harbor.toml`; `native-lockfile`
/// (if declared) is resolved relative to it. `files` is the final,
/// `.gitignore`-filtered include set as (archive-relative path, on-disk path)
/// pairs, used to compute `package-checksum`.
pub fn generate(
    manifest: &Manifest,
    package_root: &Path,
    files: &[(String, PathBuf)],
) -> Result<Lockfile, LockfileError> {
    let native_lock_checksum = match &manifest.dependencies.lockfile {
        Some(rel_path) => {
            let resolved = package_root.join(rel_path);
            if !resolved.is_file() {
                return Err(LockfileError::NativeLockfileMissing {
                    declared: rel_path.clone(),
                    resolved: resolved.display().to_string(),
                });
            }
            let hash = sha256_file(&resolved).map_err(|e| LockfileError::Io {
                path: resolved.display().to_string(),
                source: e,
            })?;
            Some(hash)
        }
        None => None,
    };

    let package_checksum = compute_package_checksum(files).map_err(|e| LockfileError::Io {
        path: "<package files>".to_string(),
        source: e,
    })?;

    Ok(Lockfile {
        spec_version: manifest.spec_version,
        harbor_version: crate::HARBOR_VERSION.to_string(),
        package_version: manifest.version.clone(),
        generated_at: now_iso8601(),
        native_manifest: manifest.dependencies.manifest.clone(),
        native_lockfile: manifest.dependencies.lockfile.clone(),
        native_lock_checksum,
        package_checksum: Some(package_checksum),
    })
}

/// Compute the `package-checksum` (SPEC.md §7.3) over a set of on-disk files.
///
/// Implements the binding convention: sort by archive-relative path (byte
/// order), skip any entry named exactly `harbor.lock`, concatenate
/// `<path>\0<sha256:hex>\n` for each remaining file (hashing its on-disk
/// contents), SHA-256 the concatenation, and render `sha256:<hex>`.
pub fn compute_package_checksum(files: &[(String, PathBuf)]) -> io::Result<String> {
    let mut entries: Vec<&(String, PathBuf)> =
        files.iter().filter(|(path, _)| path != "harbor.lock").collect();
    entries.sort_by(|a, b| a.0.as_bytes().cmp(b.0.as_bytes()));

    let mut concatenated = String::new();
    for (path, disk_path) in entries {
        let file_hash = sha256_file(disk_path)?;
        concatenated.push_str(path);
        concatenated.push('\0');
        concatenated.push_str(&file_hash);
        concatenated.push('\n');
    }

    Ok(sha256_hex(concatenated.as_bytes()))
}

/// Same digest as [`compute_package_checksum`], computed from in-memory file
/// contents rather than on-disk paths (used by the `harbor run` pipeline
/// while streaming tar entries).
pub fn compute_package_checksum_from_bytes(files: &[(String, Vec<u8>)]) -> String {
    let mut entries: Vec<&(String, Vec<u8>)> =
        files.iter().filter(|(path, _)| path != "harbor.lock").collect();
    entries.sort_by(|a, b| a.0.as_bytes().cmp(b.0.as_bytes()));

    let mut concatenated = String::new();
    for (path, contents) in entries {
        let file_hash = sha256_hex(contents);
        concatenated.push_str(path);
        concatenated.push('\0');
        concatenated.push_str(&file_hash);
        concatenated.push('\n');
    }

    sha256_hex(concatenated.as_bytes())
}

/// Current UTC time rendered as ISO 8601 (`2026-07-16T10:00:00Z`).
fn now_iso8601() -> String {
    chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{Author, Dependencies, Language, Manifest, PackageType};
    use std::fs;
    use tempfile::tempdir;

    fn sample_manifest(lockfile: Option<&str>) -> Manifest {
        Manifest {
            spec_version: 1,
            name: "my-agent".to_string(),
            version: "1.2.0".to_string(),
            description: "A test agent.".to_string(),
            package_type: PackageType::Agent,
            language: Language::Python,
            runtime: ">=3.11,<4".to_string(),
            entrypoint: "src/main.py".to_string(),
            author: Author {
                name: "Jane Doe".to_string(),
                email: "jane@example.com".to_string(),
                homepage: None,
            },
            license: "MIT".to_string(),
            dependencies: Dependencies {
                manifest: "pyproject.toml".to_string(),
                lockfile: lockfile.map(|s| s.to_string()),
            },
            permissions: vec!["network".to_string()],
            features: vec!["tools".to_string()],
            os: vec![],
            homepage: None,
            repository: None,
            documentation: None,
            port: None,
            primary_model: None,
            environment: Default::default(),
            commands: Default::default(),
            tags: vec![],
            config: Default::default(),
        }
    }

    fn write_file(dir: &Path, rel: &str, contents: &[u8]) -> PathBuf {
        let full = dir.join(rel);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(&full, contents).unwrap();
        full
    }

    // ---- Lockfile struct: TOML round-trip ----

    #[test]
    fn round_trip_preserves_all_fields() {
        let lf = Lockfile {
            spec_version: 1,
            harbor_version: "0.4.2".to_string(),
            package_version: "1.2.0".to_string(),
            generated_at: "2026-07-16T10:00:00Z".to_string(),
            native_manifest: "pyproject.toml".to_string(),
            native_lockfile: Some("uv.lock".to_string()),
            native_lock_checksum: Some("sha256:2f1e9ab3".to_string()),
            package_checksum: Some("sha256:9c4b1e02".to_string()),
        };
        let toml_str = lf.to_toml_string().expect("serialize");
        let parsed = Lockfile::from_toml_str(&toml_str).expect("parse");
        assert_eq!(lf, parsed);
    }

    #[test]
    fn skeleton_serializes_without_checksum_keys() {
        let manifest = sample_manifest(Some("uv.lock"));
        let lf = skeleton(&manifest);
        assert!(lf.package_checksum.is_none());
        assert!(lf.native_lock_checksum.is_none());

        let toml_str = lf.to_toml_string().expect("serialize");
        assert!(!toml_str.contains("package-checksum"));
        assert!(!toml_str.contains("native-lock-checksum"));
        // native-lockfile IS known statically and should be present.
        assert!(toml_str.contains("native-lockfile"));
    }

    #[test]
    fn skeleton_populates_known_keys() {
        let manifest = sample_manifest(None);
        let lf = skeleton(&manifest);
        assert_eq!(lf.spec_version, 1);
        assert_eq!(lf.harbor_version, crate::HARBOR_VERSION);
        assert_eq!(lf.package_version, "1.2.0");
        assert_eq!(lf.native_manifest, "pyproject.toml");
        assert_eq!(lf.native_lockfile, None);
        assert!(chrono::DateTime::parse_from_rfc3339(&lf.generated_at).is_ok());
    }

    // ---- compute_package_checksum: determinism ----

    #[test]
    fn checksum_is_deterministic_across_repeated_calls() {
        let dir = tempdir().unwrap();
        let a = write_file(dir.path(), "src/main.py", b"print('hi')");
        let b = write_file(dir.path(), "harbor.toml", b"name = \"x\"");

        let files = vec![
            ("src/main.py".to_string(), a.clone()),
            ("harbor.toml".to_string(), b.clone()),
        ];

        let c1 = compute_package_checksum(&files).unwrap();
        let c2 = compute_package_checksum(&files).unwrap();
        assert_eq!(c1, c2);
        assert!(c1.starts_with("sha256:"));
    }

    #[test]
    fn checksum_is_order_independent() {
        let dir = tempdir().unwrap();
        let a = write_file(dir.path(), "src/main.py", b"print('hi')");
        let b = write_file(dir.path(), "harbor.toml", b"name = \"x\"");
        let c = write_file(dir.path(), "README.md", b"# hi");

        let ordered = vec![
            ("README.md".to_string(), c.clone()),
            ("harbor.toml".to_string(), b.clone()),
            ("src/main.py".to_string(), a.clone()),
        ];
        let shuffled = vec![
            ("src/main.py".to_string(), a),
            ("README.md".to_string(), c),
            ("harbor.toml".to_string(), b),
        ];

        assert_eq!(
            compute_package_checksum(&ordered).unwrap(),
            compute_package_checksum(&shuffled).unwrap()
        );
    }

    #[test]
    fn mutating_harbor_lock_does_not_change_checksum() {
        let dir = tempdir().unwrap();
        let main_py = write_file(dir.path(), "src/main.py", b"print('hi')");
        let lock1 = write_file(dir.path(), "harbor.lock", b"package-checksum = \"old\"");

        let files1 = vec![
            ("src/main.py".to_string(), main_py.clone()),
            ("harbor.lock".to_string(), lock1.clone()),
        ];
        let checksum_before = compute_package_checksum(&files1).unwrap();

        // Mutate harbor.lock's contents.
        fs::write(&lock1, b"package-checksum = \"totally-different-value\"").unwrap();
        let checksum_after = compute_package_checksum(&files1).unwrap();

        assert_eq!(checksum_before, checksum_after);
    }

    #[test]
    fn mutating_a_non_lock_file_changes_checksum() {
        let dir = tempdir().unwrap();
        let main_py = write_file(dir.path(), "src/main.py", b"print('hi')");

        let files = vec![("src/main.py".to_string(), main_py.clone())];
        let checksum_before = compute_package_checksum(&files).unwrap();

        fs::write(&main_py, b"print('changed')").unwrap();
        let checksum_after = compute_package_checksum(&files).unwrap();

        assert_ne!(checksum_before, checksum_after);
    }

    // ---- compute_package_checksum vs compute_package_checksum_from_bytes ----

    #[test]
    fn path_based_and_bytes_based_checksum_agree() {
        let dir = tempdir().unwrap();
        let a = write_file(dir.path(), "src/main.py", b"print('hi')");
        let b = write_file(dir.path(), "harbor.toml", b"name = \"x\"");
        let lock = write_file(dir.path(), "harbor.lock", b"package-checksum = \"whatever\"");

        let path_files = vec![
            ("src/main.py".to_string(), a),
            ("harbor.toml".to_string(), b),
            ("harbor.lock".to_string(), lock),
        ];
        let bytes_files = vec![
            ("src/main.py".to_string(), b"print('hi')".to_vec()),
            ("harbor.toml".to_string(), b"name = \"x\"".to_vec()),
            (
                "harbor.lock".to_string(),
                b"package-checksum = \"whatever\"".to_vec(),
            ),
        ];

        let via_paths = compute_package_checksum(&path_files).unwrap();
        let via_bytes = compute_package_checksum_from_bytes(&bytes_files);
        assert_eq!(via_paths, via_bytes);
    }

    // ---- generate(): full population ----

    #[test]
    fn generate_populates_all_keys_with_native_lockfile() {
        let dir = tempdir().unwrap();
        write_file(dir.path(), "pyproject.toml", b"[project]\nname = \"x\"");
        let native_lock = write_file(dir.path(), "uv.lock", b"version = 1\n");
        let main_py = write_file(dir.path(), "src/main.py", b"print('hi')");

        let manifest = sample_manifest(Some("uv.lock"));
        let files = vec![
            ("src/main.py".to_string(), main_py),
            ("pyproject.toml".to_string(), dir.path().join("pyproject.toml")),
            ("uv.lock".to_string(), native_lock.clone()),
        ];

        let lf = generate(&manifest, dir.path(), &files).expect("generate should succeed");

        assert_eq!(lf.spec_version, 1);
        assert_eq!(lf.harbor_version, crate::HARBOR_VERSION);
        assert_eq!(lf.package_version, "1.2.0");
        assert_eq!(lf.native_manifest, "pyproject.toml");
        assert_eq!(lf.native_lockfile.as_deref(), Some("uv.lock"));

        let expected_lock_checksum = sha256_file(&native_lock).unwrap();
        assert_eq!(lf.native_lock_checksum, Some(expected_lock_checksum));

        assert!(lf.package_checksum.is_some());
        let expected_pkg_checksum = compute_package_checksum(&files).unwrap();
        assert_eq!(lf.package_checksum, Some(expected_pkg_checksum));

        assert!(chrono::DateTime::parse_from_rfc3339(&lf.generated_at).is_ok());
    }

    #[test]
    fn generate_omits_native_lock_checksum_when_no_native_lockfile_declared() {
        let dir = tempdir().unwrap();
        write_file(dir.path(), "pyproject.toml", b"[project]\nname = \"x\"");
        let main_py = write_file(dir.path(), "src/main.py", b"print('hi')");

        let manifest = sample_manifest(None);
        let files = vec![("src/main.py".to_string(), main_py)];

        let lf = generate(&manifest, dir.path(), &files).expect("generate should succeed");

        assert_eq!(lf.native_lockfile, None);
        assert_eq!(lf.native_lock_checksum, None);
        assert!(lf.package_checksum.is_some());
    }

    #[test]
    fn generate_errors_clearly_when_declared_native_lockfile_is_missing() {
        let dir = tempdir().unwrap();
        write_file(dir.path(), "pyproject.toml", b"[project]\nname = \"x\"");
        let main_py = write_file(dir.path(), "src/main.py", b"print('hi')");

        let manifest = sample_manifest(Some("uv.lock")); // declared but never written
        let files = vec![("src/main.py".to_string(), main_py)];

        let err = generate(&manifest, dir.path(), &files).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("uv.lock"), "error should name the missing file, got: {msg}");
    }
}
